Repository pknu-wap/Zenocide, pull requests merged in 2024-05, with the labels that each got.

#44 로비 씬 생성
  Assets/01. Scenes/Lobby.unity
  Assets/01. Scenes/Lobby.unity.meta
  Assets/02. Scripts/SceneLoader.cs
  Assets/02. Scripts/SceneLoader.cs.meta
  ProjectSettings/EditorBuildSettings.asset
Labels: 로비 씬

#48 전투 씬 화면 구성 변경
  Assets/01. Scenes/KMC/BattleTest_KMC.unity
  Assets/01. Scenes/KMC/ChangeBattleScene.unity
  Assets/01. Scenes/KMC/ChangeBattleScene.unity.meta
  Assets/02. Scripts/Battles/Character/Character.cs
  Assets/02. Scripts/Battles/Character/Enemy/Enemy.cs
  Assets/02. Scripts/Battles/UI/StatePanel.cs
  Assets/03. Prefebs/Enemy/Enemy.prefab
  Assets/03. Prefebs/UI.meta
  Assets/03. Prefebs/UI/Buff Icon.prefab
  Assets/03. Prefebs/UI/Buff Icon.prefab.meta
  Assets/03. Prefebs/UI/Debuff Panel.prefab
  Assets/03. Prefebs/UI/Debuff Panel.prefab.meta
  ProjectSettings/EditorSettings.asset
Labels: ⚔️ 전투 씬, 😎 작업 완료

#49 카드 애니메이션
  Assets/01. Scenes/KDG/BattleTest_KDG.unity
  Assets/01. Scenes/KDG/CardAnimation.unity
  Assets/01. Scenes/KDG/CardAnimation.unity.meta
  Assets/02. Scripts/Cards/CardManager.cs
  Assets/02. Scripts/TurnManager.cs
  Assets/03. Prefebs/CardBack.prefab
  Assets/03. Prefebs/CardBack.prefab.meta
  ProjectSettings/ProjectSettings.asset
Labels: ⚔️ 전투 씬, 🛠️ 작업 중

#51 배틀 씬 통합하며 테스트
  Assets/01. Scenes/BattleScene.meta
  Assets/01. Scenes/BattleScene/BattleScene.unity
  Assets/01. Scenes/BattleScene/BattleScene.unity.meta
  Assets/01. Scenes/BattleTest.unity
  Assets/02. Scripts/Cards/CardManager.cs
Labels: ⚔️ 전투 씬, 😎 작업 완료
