Repository pknu-wap/Zenocide, pull requests merged in 2024-06, with the labels that each got.

#78 튜토리얼 완성
  .gitignore
  Assets/01. Scenes/KMC/BattleScene.unity
  Assets/01. Scenes/KMC/Tutorial.unity
  Assets/01. Scenes/KMC/Tutorial.unity.meta
  Assets/02. Scripts/Battle/Cards/Deck SO/Soldier Deck.asset
  Assets/02. Scripts/Battle/Cards/Deck SO/Soldier Deck.asset.meta
  Assets/02. Scripts/Battle/Managers/GameManager.cs
  Assets/02. Scripts/Tutorial.meta
  Assets/02. Scripts/Tutorial/DiaryManager.cs
  Assets/02. Scripts/Tutorial/DiaryManager.cs.meta
  Assets/02. Scripts/Tutorial/MoveCorner.cs
  Assets/02. Scripts/Tutorial/MoveCorner.cs.meta
  Assets/02. Scripts/Tutorial/PageCurl.cs
  Assets/02. Scripts/Tutorial/PageCurl.cs.meta
  Assets/02. Scripts/Tutorial/PageScripter.cs
  Assets/02. Scripts/Tutorial/PageScripter.cs.meta
  Assets/02. Scripts/Tutorial/Supplier.cs
  Assets/02. Scripts/Tutorial/Supplier.cs.meta
  Assets/02. Scripts/etc/CSVReader.cs
  Assets/03. Prefebs/Tutorial.meta
  Assets/03. Prefebs/Tutorial/Page.prefab
  Assets/03. Prefebs/Tutorial/Page.prefab.meta
  Assets/05. Scenarios.meta
  Assets/Settings/Renderer2D.asset
  Assets/Settings/UniversalRP.asset
  Packages/manifest.json
  Packages/packages-lock.json
  ProjectSettings/GraphicsSettings.asset
  ProjectSettings/InputManager.asset
  ProjectSettings/QualitySettings.asset
  ProjectSettings/TagManager.asset
Labels: 📖 스토리 씬, 😎 작업 완료

#82 로비 화면 변경
  Assets/01. Scenes/KMC/Tutorial.unity
  Assets/01. Scenes/Lobby.unity
  Assets/01. Scenes/OMH/DeckTest.unity
  Assets/03. Prefebs/Tutorial/Page.prefab
  ProjectSettings/EditorBuildSettings.asset
Labels: 🚪 로비 씬, 😎 작업 완료

#86 카드 관련 버그 픽스
  Assets/01. Scenes/KMC/BattleScene.unity
  Assets/02. Scripts/Battle/Cards/Card.cs
  Assets/02. Scripts/Battle/Cards/CardManager.cs
  Assets/02. Scripts/Battle/Infomations/CardInfo.cs
  Assets/02. Scripts/Battle/Managers/GameManager.cs
  Assets/02. Scripts/Battle/Managers/TurnManager.cs
Labels: ⚔️ 전투 씬, 😎 작업 완료

#91 24.06.04 - 패치 노트
  Assets/01. Scenes/CDG/StoryScene.unity
  Assets/02. Scripts/Story/EventData SO/RelationEvent/RA1.asset
  Assets/02. Scripts/Story/Managers/DialogueManager.cs
  Assets/Resources/MainScript.csv
  Assets/Resources/RelationScript.csv
  Assets/Resources/SubScript.csv
Labels: 📖 스토리 씬

#94 [핫픽스] 버그 픽스
  Assets/01. Scenes/KMC/MergeScene.unity
  Assets/01. Scenes/KMC/MergeScene.unity.meta
  Assets/02. Scripts/Battle/Cards/CardManager.cs
  Assets/02. Scripts/Battle/Managers/GameManager.cs
  Assets/02. Scripts/Story/Managers/DialogueManager.cs
  Assets/02. Scripts/Story/Managers/SelectManager.cs
  Assets/02. Scripts/Story/StoryUI/CardSlot.cs
  Assets/02. Scripts/Story/StoryUI/Choice.cs
  Assets/02. Scripts/Story/StoryUI/Inventory.cs
  Assets/02. Scripts/Story/StoryUI/Items.cs
  Assets/03. Prefebs/Battle/Enemy/Enemy.prefab
  Assets/03. Prefebs/Battle/UI/Debuff Panel.prefab
  Assets/03. Prefebs/Story/UI/Choice Box.prefab
  Assets/03. Prefebs/Story/UI/Choice Box.prefab.meta
Labels: 📖 스토리 씬, 😎 작업 완료

#100 [Bug] 캔버스 충돌 해결
  Assets/01. Scenes/KMC/MergeScene.unity
  Assets/02. Scripts/Battle/Character/Enemy/Enemy SO/Normal Zombie.asset
  Assets/02. Scripts/Battle/Character/Enemy/Enemy.cs
  Assets/02. Scripts/Battle/Managers/GameManager.cs
  Assets/03. Prefebs/Story/UI/ItemSlot.prefab
  Assets/03. Prefebs/Tutorial/Page.prefab
  ProjectSettings/TagManager.asset
Labels: 😎 작업 완료, 🌌 전체

#102 버프 갱신 로직 일반화 및 덱 데이터 수정, 화상 추가
  Assets/01. Scenes/KMC/MergeScene.unity
  Assets/02. Scripts/Battle/Cards/Card SO/Amanita.asset
  Assets/02. Scripts/Battle/Cards/Card SO/Doping.asset
  Assets/02. Scripts/Battle/Cards/Card SO/Stinger.asset
  Assets/02. Scripts/Battle/Cards/Card SO/Vodka.asset
  Assets/02. Scripts/Battle/Cards/CardData.cs
  Assets/02. Scripts/Battle/Cards/Deck SO/DefaultDeck.asset
  Assets/02. Scripts/Battle/Cards/Deck SO/Reward Card List/Level 1.asset
  Assets/02. Scripts/Battle/Cards/Deck SO/Soldier Deck.asset
  Assets/02. Scripts/Battle/Character/Character.cs
  Assets/02. Scripts/Battle/Infomations/BehaviorSkillText.asset
  Assets/02. Scripts/Battle/Infomations/CardInfo.cs
  Assets/02. Scripts/Battle/Infomations/DebuffInfo.cs
Labels: ⚔️ 전투 씬, 😎 작업 완료

#103 [핫픽스] 일러스트 구조 변경
  Assets/01. Scenes/CDG/MergeScene 1.unity
  Assets/01. Scenes/KMC/MergeScene.unity
  Assets/02. Scripts/Story/Managers/DialogueManager.cs
Labels: 📖 스토리 씬
